#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["services/Boarding/Bcm.BcmAir.Boarding.Api/Bcm.BcmAir.Boarding.Api.csproj", "services/Boarding/Bcm.BcmAir.Boarding.Api/"]
RUN dotnet restore "services/Boarding/Bcm.BcmAir.Boarding.Api/Bcm.BcmAir.Boarding.Api.csproj"
COPY . .
WORKDIR "/src/services/Boarding/Bcm.BcmAir.Boarding.Api"
RUN dotnet build "Bcm.BcmAir.Boarding.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Bcm.BcmAir.Boarding.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Bcm.BcmAir.Boarding.Api.dll"]